name: ioasys_pokedex
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio:
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  flutter_native_splash: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#EC0344"
  image: "assets/images/splash.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/logo.svg
    - assets/images/icon_weight.svg
    - assets/images/icon_height.svg
    - assets/images/pokeball.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700